/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expensetracker;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author mrgonal
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_enter_username = new javax.swing.JTextField();
        name_label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        login_to_front_page = new javax.swing.JButton();
        name_label = new javax.swing.JLabel();
        login_enter_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login_enter_username.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        login_enter_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_enter_usernameActionPerformed(evt);
            }
        });

        name_label2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        name_label2.setText("Password : ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Please Login With Required Credentials");

        login_to_front_page.setBackground(new java.awt.Color(102, 0, 102));
        login_to_front_page.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        login_to_front_page.setForeground(new java.awt.Color(255, 255, 255));
        login_to_front_page.setText("Login");
        login_to_front_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_to_front_pageActionPerformed(evt);
            }
        });

        name_label.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        name_label.setText("Username : ");

        login_enter_password.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(login_to_front_page))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name_label)
                            .addComponent(name_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(login_enter_password, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login_enter_username, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_enter_username))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_enter_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(login_to_front_page)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_enter_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_enter_usernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_login_enter_usernameActionPerformed

    private void login_to_front_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_to_front_pageActionPerformed
        // TODO add your handling code here:
        if (login_enter_username.getText().trim().isEmpty() || login_enter_password.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ALL CREDENTIALS IMPORTANT FILL THEM!!");
        } else {
            SwingUtilities.invokeLater(() -> {
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    String db = "jdbc:mysql://localhost:3306/expensetracker";
                    String username = "root";
                    String password = "";

                    try (Connection con = DriverManager.getConnection(db, username, password)) {
                        // Check if the username and password are correct
                        String checkQuery = "SELECT password FROM user_detail WHERE username = ?";
                        try (PreparedStatement checkPst = con.prepareStatement(checkQuery)) {
                            checkPst.setString(1, login_enter_username.getText());
                            try (ResultSet rs = checkPst.executeQuery()) {
                                if (rs.next()) {
                                    String storedPassword = rs.getString("password");
                                    if (storedPassword.equals(login_enter_password.getText())) {
                                        // Credentials are correct, open the Expense_frame
                                        JOptionPane.showMessageDialog(this, "Login in succesful !!");
                                        openFrontPage();
                                    } else {
                                        JOptionPane.showMessageDialog(this, "Incorrect password!!");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this, "Username does not exist!!");
                                }
                            }
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "Database Driver not found: " + ex.getMessage());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
                }
            });
        }

    }//GEN-LAST:event_login_to_front_pageActionPerformed
    private void openFrontPage() {
        // Create an instance of the FrontPage
        FrontPage fp = new FrontPage(login_enter_username.getText());
        fp.setVisible(true);
        // Optionally, dispose of the current login frame
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField login_enter_password;
    private javax.swing.JTextField login_enter_username;
    private javax.swing.JButton login_to_front_page;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel name_label2;
    // End of variables declaration//GEN-END:variables
}
