/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expensetracker;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anushagonal
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_label = new javax.swing.JLabel();
        enter_username = new javax.swing.JTextField();
        name_label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Enter_btn = new javax.swing.JButton();
        login_to_front_page = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        enter_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name_label.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        name_label.setText("Username : ");

        enter_username.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        enter_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_usernameActionPerformed(evt);
            }
        });

        name_label2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        name_label2.setText("Password : ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Already Have an account? ");

        Enter_btn.setBackground(new java.awt.Color(102, 0, 102));
        Enter_btn.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Enter_btn.setForeground(new java.awt.Color(255, 255, 255));
        Enter_btn.setText("Submit");
        Enter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter_btnActionPerformed(evt);
            }
        });

        login_to_front_page.setBackground(new java.awt.Color(102, 0, 102));
        login_to_front_page.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        login_to_front_page.setForeground(new java.awt.Color(255, 255, 255));
        login_to_front_page.setText("Direct Login");
        login_to_front_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_to_front_pageActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Sign Up With Required Credentials");

        enter_password.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(login_to_front_page)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name_label))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enter_username, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(enter_password))
                        .addGap(92, 92, 92))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(Enter_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enter_username)
                    .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Enter_btn)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_to_front_page)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enter_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_usernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_enter_usernameActionPerformed

    private void Enter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enter_btnActionPerformed
        // TODO add your handling code here:
        if (enter_username.getText().trim().isEmpty() || enter_password.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ALL CREDENTIALS IMPORTANT FILL THEM!!");
        } else {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                String db = "jdbc:mysql://localhost:3306/expensetracker";
                String username = "root";
                String password = "";

                Connection con = DriverManager.getConnection(db, username, password);
                // Check if the username already exists
                String checkQuery = "SELECT COUNT(*) FROM user_detail WHERE username = ?";
                PreparedStatement checkPst = con.prepareStatement(checkQuery);
                checkPst.setString(1, enter_username.getText());
                ResultSet rs = checkPst.executeQuery();

                if (rs.next() && rs.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(this, "Username already exists!");
                } else {
                    // Insert the new user if username does not exist
                    String query = "INSERT INTO user_detail (username, password) VALUES (?, ?)";
                    PreparedStatement pst = con.prepareStatement(query);
                    pst.setString(1, enter_username.getText());
                    pst.setString(2, enter_password.getText());

                    int count = pst.executeUpdate();
                    if (count > 0) {
                        String query2 = "INSERT INTO category_table (username) VALUES (?)";
                        PreparedStatement pst2 = con.prepareStatement(query2);
                        pst2.setString(1, enter_username.getText());
                        pst2.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Signin successful! You can now login.");
                        // You can also navigate to the login page or main application page here
                        // For example:
                        // new LoginPage().setVisible(true);
                        // this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Signin FAILED!!");
                    }
                }
                con.close();//connection needs to be close

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Enter_btnActionPerformed

    private void login_to_front_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_to_front_pageActionPerformed
        // TODO add your handling code here:
        openLoginPage();

    }//GEN-LAST:event_login_to_front_pageActionPerformed
    private void openLoginPage() {
        // Create an instance of the Signup frame
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        // Optionally, dispose of the current login frame
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enter_btn;
    private javax.swing.JPasswordField enter_password;
    private javax.swing.JTextField enter_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login_to_front_page;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel name_label2;
    // End of variables declaration//GEN-END:variables
}
